### ISSUE TITLE
Change in the user DB

### ISSUE THREAD

**Issue by Swatnes64** [SocialGouv/eMJPM-api#24]
In the DB  the table 'Users" should be update with the modification of the two boolean columns "mandataire" and "service" into one in integer to define the type of person. 
something like 0 for "TI", 1 for "mandataire individuel" and 2 for "services".

**Comment by revolunet** [comment]
- ajouter une colonne users.type :
      - admin
      - individuel
      - prepose
      - service
      - ti
    - ajouter une colonne users.last_login (datetime)
    - ajouter une colonne users.active (boolean)

    - admin=true -> type=admin
    - admin=false, mandataire=ƒalse, service=true -> type=ti
    - admin=false, mandataire=true, service=true -> type=service
    - admin=false, mandataire=true, service=false -> type=mandataire
    - admin=false, mandataire=false, service=false -> type=ti
